window.MARKET_DATA = {
  "lastRun": "2026-06-22 23:34 CST",
  "generatedDate": "2026-06-22",
  "source": "akshare-public-delayed-data",
  "sourceNote": "Generated by scripts/fetch-market-data.py from AKShare, KPL when configured, and public delayed web data. Missing or failed sources fall back to data/market-seed.json.",
  "markets": {
    "cn": {
      "label": "A股",
      "summary": "2026-06-22 收盘观察：资源金属、军工航空、券商和医疗分支保持活跃。当前数据为可编辑种子数据，可替换为授权行情 API 输出。",
      "metrics": [
        {
          "name": "上证指数",
          "value": "4163.10",
          "pct": 1.78
        },
        {
          "name": "深证成指",
          "value": "16372.50",
          "pct": 2.13
        },
        {
          "name": "创业板指",
          "value": "4359.39",
          "pct": 2.52
        },
        {
          "name": "沪深300",
          "value": "5059.66",
          "pct": 2.39
        }
      ],
      "sectors": [
        {
          "name": "钨",
          "pct": 9.8,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1625",
          "moneyFlow": 1261057536.0,
          "stocks": [
            {
              "name": "中钨高新",
              "code": "000657",
              "type": "领涨股",
              "pct": 10.0
            },
            {
              "name": "章源钨业",
              "code": "002378",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "磷肥及磷化工",
          "pct": 8.97,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1435",
          "moneyFlow": 1163515264.0,
          "stocks": [
            {
              "name": "川发龙蟒",
              "code": "002312",
              "type": "领涨股",
              "pct": 9.98
            },
            {
              "name": "宏达股份",
              "code": "600331",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "钛白粉",
          "pct": 8.82,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1421",
          "moneyFlow": 406352480.0,
          "stocks": [
            {
              "name": "金浦钛业",
              "code": "000545",
              "type": "领涨股",
              "pct": 9.96
            },
            {
              "name": "钛能化学",
              "code": "002145",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "培育钻石",
          "pct": 8.76,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1023",
          "moneyFlow": 2138785792.0,
          "stocks": [
            {
              "name": "黄河旋风",
              "code": "600172",
              "type": "领涨股",
              "pct": 9.99
            },
            {
              "name": "国力电子",
              "code": "688103",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "铅锌",
          "pct": 8.03,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1614",
          "moneyFlow": 2138249408.0,
          "stocks": [
            {
              "name": "锌业股份",
              "code": "000751",
              "type": "领涨股",
              "pct": 10.1
            },
            {
              "name": "国城矿业",
              "code": "000688",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "钼",
          "pct": 7.89,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1623",
          "moneyFlow": 636972208.0,
          "stocks": [
            {
              "name": "金钼股份",
              "code": "601958",
              "type": "领涨股",
              "pct": 10.0
            },
            {
              "name": "盛龙股份",
              "code": "001257",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "橡胶助剂",
          "pct": 7.76,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1443",
          "moneyFlow": 139798416.0,
          "stocks": [
            {
              "name": "阳谷华泰",
              "code": "300121",
              "type": "领涨股",
              "pct": 10.69
            },
            {
              "name": "彤程新材",
              "code": "603650",
              "type": "活跃股"
            }
          ]
        },
        {
          "name": "文字媒体",
          "pct": 7.46,
          "status": "公开板块涨幅排行",
          "source": "东方财富板块排行",
          "code": "BK1298",
          "moneyFlow": 293699038.0,
          "stocks": [
            {
              "name": "掌阅科技",
              "code": "603533",
              "type": "领涨股",
              "pct": 9.98
            },
            {
              "name": "中文在线",
              "code": "300364",
              "type": "活跃股"
            }
          ]
        }
      ],
      "stocks": [
        {
          "name": "迪安诊断",
          "code": "300244",
          "pct": 7.62,
          "type": "涨幅/成交龙头",
          "sector": "诊断服务",
          "d5": -0.81,
          "d20": 7.15,
          "d60": 13.34,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            19.79,
            18.87,
            18.43,
            18.17,
            18.24,
            19.63
          ]
        },
        {
          "name": "金钼股份",
          "code": "601958",
          "pct": 10.0,
          "type": "资源权重龙头",
          "sector": "钨",
          "d5": 19.4,
          "d20": 39.83,
          "d60": 72.63,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            25.52,
            28.07,
            28.88,
            28.47,
            27.7,
            30.47
          ]
        },
        {
          "name": "海亮股份",
          "code": "002203",
          "pct": 3.06,
          "type": "铜链成交龙头",
          "sector": "铜",
          "d5": 12.2,
          "d20": 22.78,
          "d60": 108.56,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            23.44,
            24.79,
            24.5,
            23.2,
            25.52,
            26.3
          ]
        },
        {
          "name": "中航西飞",
          "code": "000768",
          "pct": 2.67,
          "type": "军工权重龙头",
          "sector": "航天航空",
          "d5": -7.52,
          "d20": -2.8,
          "d60": -13.47,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            22.86,
            21.63,
            21.13,
            21.29,
            20.59,
            21.14
          ]
        },
        {
          "name": "中银证券",
          "code": "601696",
          "pct": 5.73,
          "type": "券商情绪龙头",
          "sector": "券商概念",
          "d5": 16.81,
          "d20": 15.12,
          "d60": 11.13,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            11.54,
            12.69,
            13.3,
            13.15,
            12.75,
            13.48
          ]
        },
        {
          "name": "麦迪科技",
          "code": "603990",
          "pct": 0.5,
          "type": "AI医疗龙头",
          "sector": "AI制药医疗",
          "d5": -0.54,
          "d20": 29.86,
          "d60": 49.32,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-22。",
          "prices": [
            22.04,
            21.77,
            22.83,
            22.52,
            21.81,
            21.92
          ]
        }
      ]
    },
    "us": {
      "label": "美股",
      "summary": "2026-06-22 美股模块已预留结构：可接入 Nasdaq、Polygon、IEX Cloud、Alpha Vantage 等授权数据源。",
      "metrics": [
        {
          "name": "QQQ",
          "value": "740.62",
          "pct": 2.51
        },
        {
          "name": "XLK",
          "value": "191.44",
          "pct": 3.04
        },
        {
          "name": "SMH",
          "value": "659.88",
          "pct": 5.76
        },
        {
          "name": "SOXX",
          "value": "639.45",
          "pct": 6.62
        }
      ],
      "sectors": [
        {
          "name": "AI基础设施",
          "pct": 0,
          "status": "待接入实时/延迟数据"
        },
        {
          "name": "半导体",
          "pct": 0,
          "status": "适合用 SMH/SOXX 跟踪"
        },
        {
          "name": "大型科技",
          "pct": 0,
          "status": "适合用 QQQ/XLK 跟踪"
        },
        {
          "name": "软件",
          "pct": 0,
          "status": "适合用 IGV 跟踪"
        }
      ],
      "stocks": [
        {
          "name": "NVIDIA",
          "code": "NVDA",
          "pct": 2.95,
          "type": "AI芯片权重",
          "sector": "半导体",
          "d5": 2.84,
          "d20": -5.72,
          "d60": 20.26,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-18。",
          "prices": [
            204.87,
            205.19,
            212.45,
            207.41,
            204.65,
            210.69
          ]
        },
        {
          "name": "Broadcom",
          "code": "AVGO",
          "pct": 4.7,
          "type": "AI网络/ASIC",
          "sector": "半导体",
          "d5": 6.69,
          "d20": -1.53,
          "d60": 29.24,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-18。",
          "prices": [
            385.57,
            382.07,
            393.94,
            376.71,
            392.9,
            411.35
          ]
        },
        {
          "name": "Microsoft",
          "code": "MSFT",
          "pct": 0.13,
          "type": "云与AI平台",
          "sector": "大型科技",
          "d5": -2.8,
          "d20": -9.89,
          "d60": 1.79,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-18。",
          "prices": [
            390.34,
            390.74,
            399.76,
            393.83,
            378.91,
            379.4
          ]
        }
      ]
    }
  },
  "research": [
    {
      "bank": "Goldman Sachs",
      "title": "Insights: Artificial Intelligence / Markets",
      "url": "https://www.goldmansachs.com/insights/",
      "theme": "AI资本开支、市场风险、宏观与行业观点",
      "note": "公开洞察入口；部分正式研报需要机构权限。"
    },
    {
      "bank": "Goldman Sachs",
      "title": "The AI Investment Boom: When Will It Pay Off?",
      "url": "https://www.goldmansachs.com/insights/",
      "theme": "AI投资回报、半导体、数据中心、算力链",
      "note": "官网 Insights 页面列出相关播客或文章入口。"
    },
    {
      "bank": "Morgan Stanley",
      "title": "Insights: Technology & Disruption",
      "url": "https://www.morganstanley.com/insights",
      "theme": "科技颠覆、市场趋势、新兴产业",
      "note": "公开洞察入口；Research Portal/Matrix 通常需要登录。"
    },
    {
      "bank": "Morgan Stanley",
      "title": "2026 Midyear Outlooks",
      "url": "https://www.morganstanley.com/insights",
      "theme": "中期展望、资产配置、行业线索",
      "note": "官网 Insights 页面可访问公开摘要。"
    }
  ],
  "apiPlan": {
    "cn": [
      {
        "name": "Tushare Pro",
        "use": "A股日线、指数、板块、财务、公告，适合每日生成报告。",
        "note": "需要 token；部分高频数据需要积分或权限。"
      },
      {
        "name": "聚宽 / Ricequant",
        "use": "A股历史、分钟线、因子和回测，适合研究型功能。",
        "note": "通常需要账号授权，云端部署要配置密钥。"
      },
      {
        "name": "Wind / Choice",
        "use": "专业终端和机构级数据，适合严肃商业场景。",
        "note": "成本较高，但版权和稳定性最好。"
      }
    ],
    "us": [
      {
        "name": "Polygon.io",
        "use": "美股实时/延迟行情、聚合 K 线、公司事件。",
        "note": "适合实时提醒，需要付费计划。"
      },
      {
        "name": "IEX Cloud",
        "use": "美股报价、基本面、新闻。",
        "note": "API 形态友好，按量计费。"
      },
      {
        "name": "Alpha Vantage",
        "use": "美股日线、技术指标、部分免费额度。",
        "note": "适合 MVP，实时性和频率有限。"
      },
      {
        "name": "Nasdaq Data Link",
        "use": "宏观、行业、替代数据。",
        "note": "更偏研究数据，不一定适合实时提醒。"
      }
    ],
    "alerts": [
      "盘中每 1-5 分钟拉取自选股报价。",
      "对比用户设置的涨跌幅阈值、成交额、板块热度或研报关键词。",
      "触发后写入 alerts 表，并通过邮件、Telegram、企业微信、Server酱或浏览器 Push 推送。",
      "避免重复轰炸：同一股票同一规则每天只提醒一次，除非再次突破更高阈值。"
    ]
  },
  "providerStatus": {
    "cn": "Sina Finance delayed data updated 10 CN items",
    "akshareWarnings": [
      "stock_zh_a_spot_em unavailable: HTTPSConnectionPool(host='82.push2.eastmoney.com', port=443): Read timed out. (read timeout=15)",
      "stock_zh_index_spot_em unavailable: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
      "AKShare industry sectors unavailable: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
      "AKShare concept sectors unavailable: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
    ],
    "cnAkshareQuotes": "AKShare spot returned no watched stocks",
    "cnSectors": "Public sector strength updated 8 sectors",
    "us": "Sina Finance delayed data updated 7 US items"
  },
  "historyReports": [
    {
      "date": "2026-06-22",
      "file": "2026-06-22.json",
      "lastRun": "2026-06-22 23:34 CST"
    },
    {
      "date": "2026-06-19",
      "file": "2026-06-19.json",
      "lastRun": "2026-06-19 21:53 CST"
    },
    {
      "date": "2026-06-18",
      "file": "2026-06-18.json",
      "lastRun": "2026-06-18 21:46 CST"
    },
    {
      "date": "2026-06-17",
      "file": "2026-06-17.json",
      "lastRun": "2026-06-17 22:07 CST"
    },
    {
      "date": "2026-06-16",
      "file": "2026-06-16.json",
      "lastRun": "2026-06-16 23:26 CST"
    },
    {
      "date": "2026-06-15",
      "file": "2026-06-15.json",
      "lastRun": "2026-06-15 22:24 CST"
    }
  ]
};
