window.MARKET_DATA = {
  "lastRun": "2026-06-16 20:49 CST",
  "generatedDate": "2026-06-16",
  "source": "public-delayed-web-data",
  "sourceNote": "Generated by scripts/fetch-market-data.py from Sina Finance public delayed daily data. Missing or failed sources fall back to data/market-seed.json.",
  "markets": {
    "cn": {
      "label": "A股",
      "summary": "2026-06-16 收盘观察：资源金属、军工航空、券商和医疗分支保持活跃。当前数据为可编辑种子数据，可替换为授权行情 API 输出。",
      "metrics": [
        {
          "name": "上证指数",
          "value": "4091.89",
          "pct": -0.11
        },
        {
          "name": "深证成指",
          "value": "15675.25",
          "pct": 0.93
        },
        {
          "name": "创业板指",
          "value": "4102.94",
          "pct": 1.72
        },
        {
          "name": "沪深300",
          "value": "4884.23",
          "pct": -0.15
        }
      ],
      "sectors": [
        {
          "name": "AI制药医疗",
          "pct": 4.87,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "麦迪科技",
              "code": "603990",
              "pct": 4.87,
              "type": "AI医疗龙头"
            }
          ]
        },
        {
          "name": "券商概念",
          "pct": 4.81,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "中银证券",
              "code": "601696",
              "pct": 4.81,
              "type": "券商情绪龙头"
            }
          ]
        },
        {
          "name": "钨",
          "pct": 2.89,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "金钼股份",
              "code": "601958",
              "pct": 2.89,
              "type": "资源权重龙头"
            }
          ]
        },
        {
          "name": "铜",
          "pct": -1.17,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "海亮股份",
              "code": "002203",
              "pct": -1.17,
              "type": "铜链成交龙头"
            }
          ]
        },
        {
          "name": "航天航空",
          "pct": -2.31,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "中航西飞",
              "code": "000768",
              "pct": -2.31,
              "type": "军工权重龙头"
            }
          ]
        },
        {
          "name": "诊断服务",
          "pct": -2.33,
          "status": "观察池涨幅计算",
          "source": "本地观察池",
          "stocks": [
            {
              "name": "迪安诊断",
              "code": "300244",
              "pct": -2.33,
              "type": "涨幅/成交龙头"
            }
          ]
        }
      ],
      "stocks": [
        {
          "name": "迪安诊断",
          "code": "300244",
          "pct": -2.33,
          "type": "涨幅/成交龙头",
          "sector": "诊断服务",
          "d5": 10.62,
          "d20": -2.85,
          "d60": -7.25,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            16.66,
            16.64,
            16.77,
            19.79,
            18.87,
            18.43
          ]
        },
        {
          "name": "金钼股份",
          "code": "601958",
          "pct": 2.89,
          "type": "资源权重龙头",
          "sector": "钨",
          "d5": 37.85,
          "d20": 37.59,
          "d60": 38.18,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            20.95,
            21.09,
            23.2,
            25.52,
            28.07,
            28.88
          ]
        },
        {
          "name": "海亮股份",
          "code": "002203",
          "pct": -1.17,
          "type": "铜链成交龙头",
          "sector": "铜",
          "d5": 29.9,
          "d20": 19.4,
          "d60": 76.9,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            18.86,
            19.37,
            21.31,
            23.44,
            24.79,
            24.5
          ]
        },
        {
          "name": "中航西飞",
          "code": "000768",
          "pct": -2.31,
          "type": "军工权重龙头",
          "sector": "航天航空",
          "d5": 4.86,
          "d20": -9.78,
          "d60": -20.77,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            20.15,
            20.02,
            20.78,
            22.86,
            21.63,
            21.13
          ]
        },
        {
          "name": "中银证券",
          "code": "601696",
          "pct": 4.81,
          "type": "券商情绪龙头",
          "sector": "券商概念",
          "d5": 25.83,
          "d20": 10.28,
          "d60": 0.83,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            10.57,
            10.65,
            10.49,
            11.54,
            12.69,
            13.3
          ]
        },
        {
          "name": "麦迪科技",
          "code": "603990",
          "pct": 4.87,
          "type": "AI医疗龙头",
          "sector": "AI制药医疗",
          "d5": 6.83,
          "d20": 39.12,
          "d60": 47.1,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-16。",
          "prices": [
            21.37,
            21.0,
            20.04,
            22.04,
            21.77,
            22.83
          ]
        }
      ]
    },
    "us": {
      "label": "美股",
      "summary": "2026-06-16 美股模块已预留结构：可接入 Nasdaq、Polygon、IEX Cloud、Alpha Vantage 等授权数据源。",
      "metrics": [
        {
          "name": "QQQ",
          "value": "744.00",
          "pct": 3.14
        },
        {
          "name": "XLK",
          "value": "191.79",
          "pct": 3.78
        },
        {
          "name": "SMH",
          "value": "647.10",
          "pct": 4.38
        },
        {
          "name": "SOXX",
          "value": "628.45",
          "pct": 5.4
        }
      ],
      "sectors": [
        {
          "name": "AI基础设施",
          "pct": 0,
          "status": "待接入实时/延迟数据"
        },
        {
          "name": "半导体",
          "pct": 0,
          "status": "适合用 SMH/SOXX 跟踪"
        },
        {
          "name": "大型科技",
          "pct": 0,
          "status": "适合用 QQQ/XLK 跟踪"
        },
        {
          "name": "软件",
          "pct": 0,
          "status": "适合用 IGV 跟踪"
        }
      ],
      "stocks": [
        {
          "name": "NVIDIA",
          "code": "NVDA",
          "pct": 3.54,
          "type": "AI芯片权重",
          "sector": "半导体",
          "d5": 1.83,
          "d20": -5.71,
          "d60": 18.98,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-15。",
          "prices": [
            208.64,
            208.19,
            200.42,
            204.87,
            205.19,
            212.45
          ]
        },
        {
          "name": "Broadcom",
          "code": "AVGO",
          "pct": 3.11,
          "type": "AI网络/ASIC",
          "sector": "半导体",
          "d5": -0.67,
          "d20": -7.35,
          "d60": 23.17,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-15。",
          "prices": [
            396.6,
            392.16,
            372.1,
            385.57,
            382.07,
            393.94
          ]
        },
        {
          "name": "Microsoft",
          "code": "MSFT",
          "pct": 2.31,
          "type": "云与AI平台",
          "sector": "大型科技",
          "d5": -2.91,
          "d20": -5.25,
          "d60": 2.76,
          "reason": "已接入新浪财经延迟日线数据，最新交易日 2026-06-15。",
          "prices": [
            411.74,
            403.41,
            397.36,
            390.34,
            390.74,
            399.76
          ]
        }
      ]
    }
  },
  "research": [
    {
      "bank": "Goldman Sachs",
      "title": "Insights: Artificial Intelligence / Markets",
      "url": "https://www.goldmansachs.com/insights/",
      "theme": "AI资本开支、市场风险、宏观与行业观点",
      "note": "公开洞察入口；部分正式研报需要机构权限。"
    },
    {
      "bank": "Goldman Sachs",
      "title": "The AI Investment Boom: When Will It Pay Off?",
      "url": "https://www.goldmansachs.com/insights/",
      "theme": "AI投资回报、半导体、数据中心、算力链",
      "note": "官网 Insights 页面列出相关播客或文章入口。"
    },
    {
      "bank": "Morgan Stanley",
      "title": "Insights: Technology & Disruption",
      "url": "https://www.morganstanley.com/insights",
      "theme": "科技颠覆、市场趋势、新兴产业",
      "note": "公开洞察入口；Research Portal/Matrix 通常需要登录。"
    },
    {
      "bank": "Morgan Stanley",
      "title": "2026 Midyear Outlooks",
      "url": "https://www.morganstanley.com/insights",
      "theme": "中期展望、资产配置、行业线索",
      "note": "官网 Insights 页面可访问公开摘要。"
    }
  ],
  "apiPlan": {
    "cn": [
      {
        "name": "Tushare Pro",
        "use": "A股日线、指数、板块、财务、公告，适合每日生成报告。",
        "note": "需要 token；部分高频数据需要积分或权限。"
      },
      {
        "name": "聚宽 / Ricequant",
        "use": "A股历史、分钟线、因子和回测，适合研究型功能。",
        "note": "通常需要账号授权，云端部署要配置密钥。"
      },
      {
        "name": "Wind / Choice",
        "use": "专业终端和机构级数据，适合严肃商业场景。",
        "note": "成本较高，但版权和稳定性最好。"
      }
    ],
    "us": [
      {
        "name": "Polygon.io",
        "use": "美股实时/延迟行情、聚合 K 线、公司事件。",
        "note": "适合实时提醒，需要付费计划。"
      },
      {
        "name": "IEX Cloud",
        "use": "美股报价、基本面、新闻。",
        "note": "API 形态友好，按量计费。"
      },
      {
        "name": "Alpha Vantage",
        "use": "美股日线、技术指标、部分免费额度。",
        "note": "适合 MVP，实时性和频率有限。"
      },
      {
        "name": "Nasdaq Data Link",
        "use": "宏观、行业、替代数据。",
        "note": "更偏研究数据，不一定适合实时提醒。"
      }
    ],
    "alerts": [
      "盘中每 1-5 分钟拉取自选股报价。",
      "对比用户设置的涨跌幅阈值、成交额、板块热度或研报关键词。",
      "触发后写入 alerts 表，并通过邮件、Telegram、企业微信、Server酱或浏览器 Push 推送。",
      "避免重复轰炸：同一股票同一规则每天只提醒一次，除非再次突破更高阈值。"
    ]
  },
  "providerStatus": {
    "cn": "Sina Finance delayed data updated 10 CN items",
    "cnSectors": "Local watchlist sector strength fallback",
    "cnSectorWarnings": [
      "Public sector fallback unavailable: Remote end closed connection without response"
    ],
    "us": "Sina Finance delayed data updated 7 US items"
  },
  "historyReports": [
    {
      "date": "2026-06-16",
      "file": "2026-06-16.json",
      "lastRun": "2026-06-16 20:49 CST"
    },
    {
      "date": "2026-06-15",
      "file": "2026-06-15.json",
      "lastRun": "2026-06-15 22:24 CST"
    }
  ]
};
